### ISSUE TITLE
Preparation of Smart Contracts

### ISSUE THREAD

**Issue by mustyilmaz** [CankayaUniversity/ceng-407-408-2023-2024-AGRICROWD-Tarimda-Kitlesel-Fonlama-Uygulamasi#4]
- Considering possible backend scenarios.
- Completion of the testing procedures of the smart contracts.

**Comment by adiltukenmez** [comment]
Added some features to our smart contract. Now, with the help of our smart contract:

1. We can create projects.
2. We can invest or donate to the created projects.
3. We can see the value of investments and donations in both dollars and Ethereum.
4. We can record the addresses of investors and donors, along with the total amount they have invested or donated.
5. We can charge a commission from investments made for our platform (no commission is taken from donations).
6. If the investment amount exceeds the desired investment amount, the project owner can withdraw the raised money for the project.
7. We can read project details from the contract.
8. Our contract can self-deploy.
9. Upon deployment, the contract can self-verify (allowing users to see the contract's content).
10. The contract performs necessary tests internally and can automatically provide error messages when needed.

**Comment by adiltukenmez** [comment]
Fixed some bugs and added some other features to our smart contract such as:

1. A mapping structure to map the ProjectID (smart contract) and ObjectID(mongoDB) values. That way, when we send the ObjectID value to our smart contract, it will be automatically converted to ProjectID
2. Fixed the bugs caused by ObjectID
3. Fixed the donation bug

**Comment by adiltukenmez** [comment]
The final version of the smart contract is implemented.
