### ISSUE TITLE
Features of "My-Projects" that need improvement.

### ISSUE THREAD

**Issue by adiltukenmez** [CankayaUniversity/ceng-407-408-2023-2024-AGRICROWD-Tarimda-Kitlesel-Fonlama-Uygulamasi#81]

**Comment by mustyilmaz** [comment]
- [ ] When the user enters my-projects, he/she should see the minimum information about his/her project as a card.
- [ ] When users click on one of these cards, they should be able to observe the preview of the project page and other information separately.

**Comment by mustyilmaz** [comment]
- [ ] By making the project card clickable, if the project reaches the targeted investment amount before the end of the project book collection period, the relevant user should be able to withdraw this amount from the relevant project card to his/her own wallet.
- [ ] At the same time, it should be possible to state that it has made a profit from this tab and send the profit amount to the users or directly to the platform wallet address in order to distribute the profit.

**Comment by mustyilmaz** [comment]
Additionally, projects are now separated into active and inactive categories. With all these developments, this issue has been resolved.
